### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by jimwormold** [burnpiro/farm-animal-tracking#7]
Hi

Looks like great stuff here, but I'm struggling to run it as I'm not sure what tensorflow version to use (I've tried the latest 2.7 and 1.15, but it looks like it's one of the inbetween versions!). Apologies if it's in the documentation somewhere but I couldn't find it.

best wishes

**Comment by burnpiro** [comment]
Hi,

I've checked the conda env and it should be 2.3.0. If that doesn't work try 2.2 because I'm not sure that someone changed it or now. I've copied all the versions into the [requirements.txt](https://github.com/burnpiro/farm-animal-tracking/blob/main/requirements.txt#L2) for your convenience.

Cheers

**Comment by jimwormold** [comment]
Brilliant! Thanks very much
