### ISSUE TITLE
Access to data for trying out the code

### ISSUE THREAD

**Issue by pictus-ai** [burnpiro/farm-animal-tracking#8]
Hi Kemal,
I was trying to get the data from the provided weblink, but the webpage seems to not be accessible. Is their another way I can get the data to try out your code for the Project?
psrg.unl.edu/Projects/Details/12-Animal-Tracking

**Comment by burnpiro** [comment]
I no longer have the original dataset. The page is available on the web archive [https://web.archive.org/web/20200202012909/https://psrg.unl.edu/Projects/Details/12-Animal-Tracking](https://web.archive.org/web/20200202012909/https://psrg.unl.edu/Projects/Details/12-Animal-Tracking)
But the link to the zip file doesn't work either. I think you could try to contact the university directly because they should have a copy somewhere. If they have any other link to the dataset, could you share it here, so anyone can see it in the future?

**Comment by pictus-ai** [comment]
Thanks for the quick response Kemal. I will try to contact university, the lab's page [https://psrg.unl.edu/] is also not working so maybe the faculty is not at the university anymore. I will share the link if I get a response.

**Comment by xin4431** [comment]
Did you get the data?

**Comment by yoletPig** [comment]
Did you have another pigs tracking dataset?

**Comment by pictus-ai** [comment]
@xin4431, yes I was able to contact the university [Dr. Eric Posta, https://directory.unl.edu/people/epsota2] and get some data links. I got busy with other things, so haven't actually tried to implement any of it Or focus on the project.  Not sure I can share directly without his permission..I can contact him again and request him to maybe provide a download link that can be shared here for everyone, OR you can try to contact him (see public contact info above link)?
